import java.util.Enumeration;

import javax.swing.AbstractButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jmulh
 */
public class employee extends javax.swing.JFrame {
    Backend backend = new Backend();
    String empID ="";
    /**
     * Creates new form employee
     */
    public employee(int al, String name, String ID, String ssn, String[] devices, int employeeAL) {
        initComponents();
        empID = ID;
        employeeNameText.setText(name);
        employeeIDText.setText(ID);
        if(al == backend.getMaxAccessLevel()){
            employeeSSNText.setText(ssn);
        }
        else{
            employeeSSNText.setText("*********");
        }
        devicesText.setText(buildDevicesString(devices));
        empAccessLevelText.setText(Integer.toString(employeeAL));
        empLocationLbl.setText(backend.getEmployeeLocationByID(ID));
        empWorkingHoursFld.setText(Integer.toString(backend.getEmployeeWorkingHoursByID(ID)));

    }

    public String buildDevicesString(String[] devices){
        String deviceString = "";
        for(int i = 0; i < devices.length; i++){
            deviceString += devices[i] + ", ";
        }
        if(deviceString == ""){
            return "None";
        }
        return deviceString;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accessLevelButtons = new javax.swing.ButtonGroup();
        employeeNameText = new javax.swing.JLabel();
        employeeIDText = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        setEmployeeLevel = new javax.swing.JButton();
        threeBtn = new javax.swing.JRadioButton();
        twoBtn = new javax.swing.JRadioButton();
        oneBtn = new javax.swing.JRadioButton();
        remEmpBtn = new javax.swing.JRadioButton();
        devicesText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        empAccessLevelText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        empWorkingHoursLbl = new javax.swing.JLabel();
        employeeSSNText = new javax.swing.JTextField();
        empLocationLbl = new javax.swing.JTextField();
        empWorkingHoursFld = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        employeeNameText.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        employeeNameText.setText("Employee Name");

        employeeIDText.setText("Employee ID");

        jLabel3.setText("Current Devices Owned");

        setEmployeeLevel.setText("Update Employee");
        setEmployeeLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setEmployeeLevelActionPerformed(evt);
            }
        });

        accessLevelButtons.add(threeBtn);
        threeBtn.setText("3");

        accessLevelButtons.add(twoBtn);
        twoBtn.setText("2");

        accessLevelButtons.add(oneBtn);
        oneBtn.setText("1");

        accessLevelButtons.add(remEmpBtn);
        remEmpBtn.setText("Remove Employee");

        devicesText.setText("Devices");

        jLabel1.setText("Current Access Level:");

        empAccessLevelText.setText("accessLevel");

        jLabel2.setText("ID:");

        jLabel4.setText("SSN:");

        jLabel5.setText("Location:");

        empWorkingHoursLbl.setText("Working Hours:");

        employeeSSNText.setText("EmployeeSSN");
        employeeSSNText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeSSNTextActionPerformed(evt);
            }
        });

        empLocationLbl.setText("EmployeeLocation");

        empWorkingHoursFld.setText("Employee Working Hours");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(employeeNameText))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(twoBtn)
                            .addComponent(threeBtn)
                            .addComponent(oneBtn)
                            .addComponent(remEmpBtn)
                            .addComponent(setEmployeeLevel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(employeeSSNText, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(employeeIDText))
                            .addComponent(jLabel5)
                            .addComponent(empWorkingHoursLbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(devicesText))
                        .addGap(18, 18, 18)
                        .addComponent(empAccessLevelText))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(empLocationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empWorkingHoursFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(employeeNameText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeIDText)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(employeeSSNText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(devicesText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(empLocationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empWorkingHoursLbl)
                    .addComponent(empWorkingHoursFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(empAccessLevelText))
                .addGap(18, 18, 18)
                .addComponent(threeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oneBtn)
                .addGap(3, 3, 3)
                .addComponent(remEmpBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(setEmployeeLevel)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setEmployeeLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setEmployeeLevelActionPerformed
        for(Enumeration<AbstractButton> buttons = accessLevelButtons.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            String buttonText = button.getText();
            if (buttonText.equals("Remove Employee")) {
                buttonText = "0";
            }

            if(button.isSelected()) {
                backend.setEmployeeAccessLevelByID(empID, Integer.parseInt(buttonText));
                empAccessLevelText.setText(Integer.toString(backend.getAccessLevelByID(empID)));
            }
        }
        int workingHours = backend.getEmployeeWorkingHoursByID(empID);
        try{
            workingHours = Integer.parseInt(empWorkingHoursFld.getText());
        }
        catch (NumberFormatException e){
            System.out.println("Invalid input");
        }
        backend.updateEmployeeSSNByID(empID, employeeSSNText.getText());
        backend.updateEmployeeLocationByID(empID, empLocationLbl.getText());
        backend.updateEmployeeWorkingHoursByID(empID, workingHours);
        employeeSSNText.setText(backend.getEmployeeSSNByID(empID));
        empLocationLbl.setText(backend.getEmployeeLocationByID(empID));
        empWorkingHoursFld.setText(Integer.toString(backend.getEmployeeWorkingHoursByID(empID)));
    }//GEN-LAST:event_setEmployeeLevelActionPerformed

    private void employeeSSNTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeSSNTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeSSNTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee(0, "", "", "" , new String[0], 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup accessLevelButtons;
    private javax.swing.JLabel devicesText;
    private javax.swing.JLabel empAccessLevelText;
    private javax.swing.JTextField empLocationLbl;
    private javax.swing.JTextField empWorkingHoursFld;
    private javax.swing.JLabel empWorkingHoursLbl;
    private javax.swing.JLabel employeeIDText;
    private javax.swing.JLabel employeeNameText;
    private javax.swing.JTextField employeeSSNText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton oneBtn;
    private javax.swing.JRadioButton remEmpBtn;
    private javax.swing.JButton setEmployeeLevel;
    private javax.swing.JRadioButton threeBtn;
    private javax.swing.JRadioButton twoBtn;
    // End of variables declaration//GEN-END:variables
}
