import java.util.ArrayList;
import java.util.HashMap;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jmulh
 */
public class Homepage extends javax.swing.JFrame {
    Backend backend = new Backend();
    String userID;

    /**
     * Creates new form Homepage
     * @param aL
     */
    public Homepage(String userID) {
        initComponents();
        setPanelsInvisible();
        this.userID = userID;
        int accessLevel = backend.getAccessLevelByID(userID);
        if(accessLevel < backend.getMaxAccessLevel()){
            createUserBtn.setVisible(false);
        }
    }
    private void setPanelsInvisible(){
        SuppliesPnl.setVisible(false);
        SuppliersPnl.setVisible(false);
        UsersPnl.setVisible(false);
        MaintenancePnl.setVisible(false);
        sideBarPnl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        MaintenancePnl = new javax.swing.JPanel();
        mtncIDTxt = new javax.swing.JTextField();
        searchBtn4 = new javax.swing.JButton();
        createRepairBtn = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        issueLbl = new javax.swing.JLabel();
        costLbl = new javax.swing.JLabel();
        fixedByLbl = new javax.swing.JLabel();
        fixedDateLbl = new javax.swing.JLabel();
        deviceSNLbl = new javax.swing.JLabel();
        showMaitenanceBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        SuppliersPnl = new javax.swing.JPanel();
        supplierTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        supplierNameLbl = new javax.swing.JLabel();
        supplierPhoneLbl = new javax.swing.JLabel();
        supplierAddressLbl = new javax.swing.JLabel();
        supplierEmailLbl = new javax.swing.JLabel();
        suppliesLbl = new javax.swing.JLabel();
        viewSupplierBtn = new javax.swing.JButton();
        searchBtn2 = new javax.swing.JButton();
        createSupplierBtn = new javax.swing.JButton();
        SuppliesPnl = new javax.swing.JPanel();
        searchBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        supplyTxt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        checkOutBtn = new javax.swing.JButton();
        checkInBtn = new javax.swing.JButton();
        itemNameLbl = new javax.swing.JLabel();
        itemModelLbl = new javax.swing.JLabel();
        deviceLbl = new javax.swing.JLabel();
        currOwnerLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        viewItemBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        registerSupply = new javax.swing.JButton();
        UsersPnl = new javax.swing.JPanel();
        empIDText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        empNameLbl = new javax.swing.JLabel();
        empDevicesLbl = new javax.swing.JLabel();
        viewItemLbl2 = new javax.swing.JButton();
        searchBtn3 = new javax.swing.JButton();
        createUserBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        sideBarPnl = new javax.swing.JPanel();
        viewSuppliesBtn = new javax.swing.JButton();
        viewUserBtn = new javax.swing.JButton();
        ViewSuppliersBtn = new javax.swing.JButton();
        viewRostersBtn = new javax.swing.JButton();
        viewRepairsBtn = new javax.swing.JButton();
        hamburgerBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel1.setMaximumSize(new java.awt.Dimension(517, 436));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(514, 436));
        jPanel1.setLayout(new java.awt.CardLayout());

        MaintenancePnl.setMaximumSize(new java.awt.Dimension(517, 436));
        MaintenancePnl.setPreferredSize(new java.awt.Dimension(517, 436));

        mtncIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtncIDTxtActionPerformed(evt);
            }
        });

        searchBtn4.setText("Search");
        searchBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn4ActionPerformed(evt);
            }
        });

        createRepairBtn.setText("Register Repair");
        createRepairBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRepairBtnActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        issueLbl.setText("Issue");

        costLbl.setText("Cost");

        fixedByLbl.setText("Fixed By");

        fixedDateLbl.setText("When It was Fixed?");

        deviceSNLbl.setText("Device SN");

        showMaitenanceBtn.setText("Update");
        showMaitenanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMaitenanceBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showMaitenanceBtn)
                .addGap(27, 27, 27)
                .addComponent(issueLbl)
                .addGap(27, 27, 27)
                .addComponent(costLbl)
                .addGap(18, 18, 18)
                .addComponent(fixedByLbl)
                .addGap(119, 119, 119)
                .addComponent(deviceSNLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(fixedDateLbl)
                .addGap(40, 40, 40))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issueLbl)
                    .addComponent(costLbl)
                    .addComponent(fixedByLbl)
                    .addComponent(fixedDateLbl)
                    .addComponent(deviceSNLbl)
                    .addComponent(showMaitenanceBtn))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jLabel6.setText("Maintenance Number");

        javax.swing.GroupLayout MaintenancePnlLayout = new javax.swing.GroupLayout(MaintenancePnl);
        MaintenancePnl.setLayout(MaintenancePnlLayout);
        MaintenancePnlLayout.setHorizontalGroup(
            MaintenancePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaintenancePnlLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(mtncIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createRepairBtn)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MaintenancePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        MaintenancePnlLayout.setVerticalGroup(
            MaintenancePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaintenancePnlLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(MaintenancePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mtncIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn4)
                    .addComponent(createRepairBtn)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        jPanel1.add(MaintenancePnl, "card2");

        SuppliersPnl.setMaximumSize(new java.awt.Dimension(517, 436));
        SuppliersPnl.setOpaque(false);
        SuppliersPnl.setPreferredSize(new java.awt.Dimension(517, 436));

        supplierTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierTxtActionPerformed(evt);
            }
        });

        jLabel2.setText("Supplier Name:");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        supplierNameLbl.setText("NAME");

        supplierPhoneLbl.setText("Phone");

        supplierAddressLbl.setText("Address");

        supplierEmailLbl.setText("Email");

        suppliesLbl.setText("Supplies:");

        viewSupplierBtn.setText("View");
        viewSupplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSupplierBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewSupplierBtn)
                .addGap(76, 76, 76)
                .addComponent(supplierNameLbl)
                .addGap(18, 18, 18)
                .addComponent(supplierPhoneLbl)
                .addGap(18, 18, 18)
                .addComponent(supplierAddressLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(supplierEmailLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(suppliesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierNameLbl)
                    .addComponent(supplierPhoneLbl)
                    .addComponent(supplierAddressLbl)
                    .addComponent(supplierEmailLbl)
                    .addComponent(suppliesLbl)
                    .addComponent(viewSupplierBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchBtn2.setText("Search");
        searchBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn2ActionPerformed(evt);
            }
        });

        createSupplierBtn.setText("Create Supplier");
        createSupplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSupplierBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SuppliersPnlLayout = new javax.swing.GroupLayout(SuppliersPnl);
        SuppliersPnl.setLayout(SuppliersPnlLayout);
        SuppliersPnlLayout.setHorizontalGroup(
            SuppliersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SuppliersPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(SuppliersPnlLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(supplierTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchBtn2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createSupplierBtn)
                .addGap(60, 60, 60))
        );
        SuppliersPnlLayout.setVerticalGroup(
            SuppliersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuppliersPnlLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(SuppliersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(supplierTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn2)
                    .addComponent(createSupplierBtn))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(SuppliersPnl, "card3");

        SuppliesPnl.setMaximumSize(new java.awt.Dimension(517, 436));
        SuppliesPnl.setPreferredSize(new java.awt.Dimension(517, 436));

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Item SN:");

        supplyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplyTxtActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        checkOutBtn.setText("Out");
        checkOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutBtnActionPerformed(evt);
            }
        });

        checkInBtn.setText("In");
        checkInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInBtnActionPerformed(evt);
            }
        });

        itemNameLbl.setText("NAME");

        itemModelLbl.setText("Model");

        deviceLbl.setText("Type of Device");

        currOwnerLbl.setText("Who has?");

        passwordLbl.setText("Password: ");

        viewItemBtn.setText("View");
        viewItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewItemBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(itemNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deviceLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(currOwnerLbl)
                .addGap(18, 18, 18)
                .addComponent(itemModelLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(viewItemBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deviceLbl)
                        .addComponent(currOwnerLbl)
                        .addComponent(itemNameLbl)
                        .addComponent(itemModelLbl)
                        .addComponent(passwordLbl)
                        .addComponent(viewItemBtn))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(checkOutBtn)
                        .addComponent(checkInBtn)))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        registerSupply.setText("Register Supply");
        registerSupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerSupplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SuppliesPnlLayout = new javax.swing.GroupLayout(SuppliesPnl);
        SuppliesPnl.setLayout(SuppliesPnlLayout);
        SuppliesPnlLayout.setHorizontalGroup(
            SuppliesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuppliesPnlLayout.createSequentialGroup()
                .addGroup(SuppliesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SuppliesPnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SuppliesPnlLayout.createSequentialGroup()
                        .addGroup(SuppliesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SuppliesPnlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SuppliesPnlLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36)
                                .addComponent(supplyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(searchBtn)
                                .addGap(41, 41, 41)
                                .addComponent(registerSupply)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        SuppliesPnlLayout.setVerticalGroup(
            SuppliesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuppliesPnlLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(SuppliesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(supplyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn)
                    .addComponent(registerSupply))
                .addGap(30, 30, 30)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(785, 785, 785)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(SuppliesPnl, "card4");

        UsersPnl.setMaximumSize(new java.awt.Dimension(517, 436));
        UsersPnl.setPreferredSize(new java.awt.Dimension(517, 436));

        empIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empIDTextActionPerformed(evt);
            }
        });

        jLabel3.setText("Employee ID/Name:");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        empNameLbl.setText("NAME");

        empDevicesLbl.setText("Devices Owned: ");

        viewItemLbl2.setText("View");
        viewItemLbl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewItemLbl2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewItemLbl2)
                .addGap(76, 76, 76)
                .addComponent(empNameLbl)
                .addGap(44, 44, 44)
                .addComponent(empDevicesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empNameLbl)
                    .addComponent(empDevicesLbl)
                    .addComponent(viewItemLbl2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchBtn3.setText("Search");
        searchBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn3ActionPerformed(evt);
            }
        });

        createUserBtn.setText("Register Employee");
        createUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UsersPnlLayout = new javax.swing.GroupLayout(UsersPnl);
        UsersPnl.setLayout(UsersPnlLayout);
        UsersPnlLayout.setHorizontalGroup(
            UsersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsersPnlLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(empIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createUserBtn)
                .addGap(30, 30, 30))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        UsersPnlLayout.setVerticalGroup(
            UsersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsersPnlLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(UsersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(searchBtn3)
                    .addComponent(createUserBtn))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(UsersPnl, "card2");

        jPanel4.setLayout(new java.awt.CardLayout());

        sideBarPnl.setBackground(new java.awt.Color(153, 0, 255));

        viewSuppliesBtn.setText("View Supplies");
        viewSuppliesBtn.setPreferredSize(new java.awt.Dimension(125, 23));
        viewSuppliesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSuppliesBtnActionPerformed(evt);
            }
        });
        sideBarPnl.add(viewSuppliesBtn);

        viewUserBtn.setText("View Users");
        viewUserBtn.setPreferredSize(new java.awt.Dimension(125, 23));
        viewUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUserBtnActionPerformed(evt);
            }
        });
        sideBarPnl.add(viewUserBtn);

        ViewSuppliersBtn.setText("View Suppliers");
        ViewSuppliersBtn.setPreferredSize(new java.awt.Dimension(125, 23));
        ViewSuppliersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewSuppliersBtnActionPerformed(evt);
            }
        });
        sideBarPnl.add(ViewSuppliersBtn);

        viewRostersBtn.setText("View Rosters");
        viewRostersBtn.setPreferredSize(new java.awt.Dimension(125, 23));
        viewRostersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRostersBtnActionPerformed(evt);
            }
        });
        sideBarPnl.add(viewRostersBtn);

        viewRepairsBtn.setText("View Repairs");
        viewRepairsBtn.setMaximumSize(new java.awt.Dimension(127, 180));
        viewRepairsBtn.setPreferredSize(new java.awt.Dimension(125, 23));
        viewRepairsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRepairsBtnActionPerformed(evt);
            }
        });
        sideBarPnl.add(viewRepairsBtn);

        hamburgerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icons8-menu-30.png"))); // NOI18N
        hamburgerBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        hamburgerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamburgerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hamburgerBtn)
                            .addComponent(sideBarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hamburgerBtn)
                        .addGap(18, 18, 18)
                        .addComponent(sideBarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewSuppliesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSuppliesBtnActionPerformed
        setPanelsInvisible();
        SuppliesPnl.setVisible(true);
    }//GEN-LAST:event_viewSuppliesBtnActionPerformed

    private void viewUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUserBtnActionPerformed
        setPanelsInvisible();
        UsersPnl.setVisible(true);
    }//GEN-LAST:event_viewUserBtnActionPerformed

    private void itemTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemTextActionPerformed

    private void checkOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutBtnActionPerformed
        checkInBtnActionPerformed(evt);
    }//GEN-LAST:event_checkOutBtnActionPerformed

    private void checkInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInBtnActionPerformed
       CheckInOutSupply checkInOutSupply = new CheckInOutSupply(itemNameLbl.getText(), itemText.getText());
        checkInOutSupply.setVisible(true);
    }//GEN-LAST:event_checkInBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        System.out.println("Searched");
        String dataRequested = "";
        if(SuppliesPnl.isVisible()){
            dataRequested = "supplies";
        }
        else if (UsersPnl.isVisible()){
            dataRequested = "users";
        }
        else if (SuppliersPnl.isVisible()){
            dataRequested = "suppliers";
        }
        else if (MaintenancePnl.isVisible()){
            dataRequested = "maintenance";
        }
        else{
            System.out.println("Error: No panel is visible");
        }
        HashMap<String,String> result = backend.fetchPnlObjectItems(itemText.getText(), dataRequested);
        if(result != null){
            if(dataRequested.equals("supplies")){
                itemNameLbl.setText(result.get("Name")); 
                itemModelLbl.setText(result.get("Model"));
                deviceLbl.setText(result.get("Device"));
                currOwnerLbl.setText(result.get("Owner"));
                passwordLbl.setText(result.get("Password"));
            }
            if(dataRequested.equals("suppliers")){
                supplierNameLbl.setText(result.get("Name"));
                supplierAddressLbl.setText(result.get("Address"));
                supplierPhoneLbl.setText(result.get("Phone"));
                supplierEmailLbl.setText(result.get("Email"));
                suppliesLbl.setText(result.get("itemsSupplied"));
            }
            if(dataRequested.equals("users")){
                empNameLbl.setText(result.get("Name"));
                empDevicesLbl.setText(result.get("Devices"));
            }
            if(dataRequested.equals("maintenance")){
                issueLbl.setText("issue");
                costLbl.setText("cost");
                fixedByLbl.setText("fixedBy");
                deviceSNLbl.setText("deviceSN");
                fixedDateLbl.setText("fixedDate");

            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void itemText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemText1ActionPerformed

    private void searchBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn2ActionPerformed
        searchBtnActionPerformed(evt);
    }//GEN-LAST:event_searchBtn2ActionPerformed

    private void itemText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemText2ActionPerformed

    private void searchBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn3ActionPerformed
        searchBtnActionPerformed(evt);
    }//GEN-LAST:event_searchBtn3ActionPerformed

    private void hamburgerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamburgerBtnActionPerformed
        sideBarPnl.setVisible(true);
    }//GEN-LAST:event_hamburgerBtnActionPerformed

    private void viewItemLbl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewItemLbl2ActionPerformed
        String empID = empIDText.getText();
        employee employee = new employee(backend.getAccessLevelByID(empID), backend.getEmployeeNameByID(empID), empID, backend.getEmployeeSSNByID(empID), backend.getEmployeeDevicesByID(empID), backend.getAccessLevelByID(empID));
        employee.setVisible(true);
    }//GEN-LAST:event_viewItemLbl2ActionPerformed

    private void createUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserBtnActionPerformed
        newUser newUser = new newUser(1);
        newUser.setVisible(true);
    }//GEN-LAST:event_createUserBtnActionPerformed

    private void ViewSuppliersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewSuppliersBtnActionPerformed
        setPanelsInvisible();
        SuppliersPnl.setVisible(true);
    }//GEN-LAST:event_ViewSuppliersBtnActionPerformed

    private void viewRostersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRostersBtnActionPerformed
        setPanelsInvisible();
        supplyRoster supplyRoster = new supplyRoster();
        supplyRoster.setVisible(true);
    }//GEN-LAST:event_viewRostersBtnActionPerformed

    private void viewRepairsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRepairsBtnActionPerformed
        setPanelsInvisible();
        MaintenancePnl.setVisible(true);
    }//GEN-LAST:event_viewRepairsBtnActionPerformed

    private void createRepairBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRepairBtnActionPerformed
        maintenance maintenance = new maintenance();
        maintenance.setVisible(true);
    }//GEN-LAST:event_createRepairBtnActionPerformed

    private void searchBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn4ActionPerformed
        searchBtnActionPerformed(evt);
    }//GEN-LAST:event_searchBtn4ActionPerformed

    private void empIDText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empIDText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empIDText1ActionPerformed

    private void showMaitenanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMaitenanceBtnActionPerformed
        maintenance maintenance = new maintenance(mtncIDTxt.getText());
        maintenance.setVisible(true);
        
    }//GEN-LAST:event_showMaitenanceBtnActionPerformed

    private void viewItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewItemBtnActionPerformed
        supply supply = new supply(itemText.getText());
        supply.setVisible(true);
    }//GEN-LAST:event_viewItemBtnActionPerformed

    private void registerSupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerSupplyActionPerformed
        newSupply newSupply = new newSupply();
        newSupply.setVisible(true);
    }//GEN-LAST:event_registerSupplyActionPerformed

    private void viewSupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSupplierBtnActionPerformed
        supplier supplier = new supplier(supplierNameLbl.getText());
        supplier.setVisible(true);
    }//GEN-LAST:event_viewSupplierBtnActionPerformed

    private void createSupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSupplierBtnActionPerformed
        newSupplier newSupplier = new newSupplier();
        newSupplier.setVisible(true);
    }//GEN-LAST:event_createSupplierBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MaintenancePnl;
    private javax.swing.JPanel SuppliersPnl;
    private javax.swing.JPanel SuppliesPnl;
    private javax.swing.JPanel UsersPnl;
    private javax.swing.JButton ViewSuppliersBtn;
    private javax.swing.JButton checkInBtn;
    private javax.swing.JButton checkOutBtn;
    private javax.swing.JLabel costLbl;
    private javax.swing.JButton createRepairBtn;
    private javax.swing.JButton createSupplierBtn;
    private javax.swing.JButton createUserBtn;
    private javax.swing.JLabel currOwnerLbl;
    private javax.swing.JLabel deviceLbl;
    private javax.swing.JLabel deviceSNLbl;
    private javax.swing.JLabel empDevicesLbl;
    private javax.swing.JTextField empIDText;
    private javax.swing.JLabel empNameLbl;
    private javax.swing.JLabel fixedByLbl;
    private javax.swing.JLabel fixedDateLbl;
    private javax.swing.JButton hamburgerBtn;
    private javax.swing.JLabel issueLbl;
    private javax.swing.JLabel itemModelLbl;
    private javax.swing.JLabel itemNameLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField mtncIDTxt;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JButton registerSupply;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton searchBtn2;
    private javax.swing.JButton searchBtn3;
    private javax.swing.JButton searchBtn4;
    private javax.swing.JButton showMaitenanceBtn;
    private javax.swing.JPanel sideBarPnl;
    private javax.swing.JLabel supplierAddressLbl;
    private javax.swing.JLabel supplierEmailLbl;
    private javax.swing.JLabel supplierNameLbl;
    private javax.swing.JLabel supplierPhoneLbl;
    private javax.swing.JTextField supplierTxt;
    private javax.swing.JLabel suppliesLbl;
    private javax.swing.JTextField supplyTxt;
    private javax.swing.JButton viewItemBtn;
    private javax.swing.JButton viewItemLbl2;
    private javax.swing.JButton viewRepairsBtn;
    private javax.swing.JButton viewRostersBtn;
    private javax.swing.JButton viewSupplierBtn;
    private javax.swing.JButton viewSuppliesBtn;
    private javax.swing.JButton viewUserBtn;
    // End of variables declaration//GEN-END:variables
}
